Fix for KeyError for optimizer_params
KeyError: 'The following keys in the config file were not used, did you make a typo?: optimizer_params

Support dropped for _params as of 0.6 https://github.com/mir-group/nequip/pull/429